language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install pylint
# command to run tests
script:
  - pylint --rcfile=.pylintrc $(git diff --name-only $TRAVIS_BRANCH...HEAD | grep .py)
