language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install pylint
  - pip install flask
  - pip install flask_restful
  - pip install pycurl
# command to run tests
script:
  - pylint --rcfile=.pylintrc *.py
